### ISSUE TITLE
verify_signature might need a network flag

### ISSUE THREAD

**Issue by rllola** [Zondax/filecoin-rs#86]
If I am not mistaken we have the same issue with `verify_signature` than with `recover_key`.

We should also have a flag in order to specify the network when matching the recovered address from the signature and address extracted from the tx.

```
    // Compare recovered public key with the public key from the transaction
    if tx_from != from.to_string() {
        return Ok(false);
    }
```

**Comment by jleni** [comment]
This is discussible as verification is different from recovery.

In recovery, the caller, given a private key want to retrieve a properly formatted address for network X. So the network parameter is required.

In verify, the situation is different. Given that filecoin does not contain a chainid in the transaction ( this is by design as discussed in this issue https://github.com/filecoin-project/lotus/issues/1138#issuecomment-577735251)

While the json input indicates the network (f or t), this information is not really part of the transaction (when CBOR encoded) but some additional information that is only available the formatting of the address.

We could run a check by looking at the first characted in the address (f or t).. but I am not 100% sure about this.

@eshon any feedback?

**Comment by rllola** [comment]
Ah yes. My bad I forgot that we were taking a cbor format of the transaction. I just focused on the comparison we were doing.

**Comment by eshon** [comment]
@jleni - Can you just verify without the network id and just use f or t for now?
