### ISSUE TITLE
Add BLS support

### ISSUE THREAD

**Issue by jleni** [Zondax/filecoin-rs#97]
- [x] Adjust/extend API to add support to Rust native library
- [x] Add WASM support if possible
- [x] Update documentation
If WASM support it not possible due to std limitations, let's create a new issue to track this additional work.
Reference: https://github.com/filecoin-project/bls-signatures
If we find Ideally we don't need to modify the rust library much.

**Comment by rllola** [comment]
The WASM lib doesn't want to compile because of the dependencies of a rust libraries which has a assembly component.

https://github.com/filecoin-project/bls-signatures/blob/master/Cargo.toml#L19

Two options to solve this :
- Find a way to compile assembly code for WASM
- Use a pure rust `ff` lib

This assembly code seems to be present to avoid side channel attack. First option should be favored but option 2 is also acceptable but might required an assessment of the risks of this attack in WASM.

**Comment by jleni** [comment]
This will be solved as part of https://github.com/Zondax/filecoin-rs/pull/117
As soon as that is merge you should be able to continue

**Comment by rllola** [comment]
closed with https://github.com/Zondax/filecoin-rs/pull/122
